twilio_contacts/urls.py
from django.contrib import admin
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from django.urls import path, include

from contact.views import IndexView, ContactCreateView, ContactDetailView, MessageCreateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name="index_view"),
    path('register/', CreateView.as_view(
        template_name='register.html',
        form_class=UserCreationForm,
        success_url='/'
    ), name="register_view"),
    path('contact/new', ContactCreateView.as_view(), name='contact_create_view'),
    path('contact/<int:pk>/', ContactDetailView.as_view(), name='contact_detail_view'),
    path('contact/<int:pk>/message/new', MessageCreateView.as_view(), name='message_create_view'),
    path('accounts/', include('django.contrib.auth.urls')),

]

contact/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse


class Contact(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    number = models.CharField(max_length=20, validators=[RegexValidator(regex=r'^\d{10}$')])
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    @property
    def full_name(self):
        return "{} {}".format(self.first_name, self.last_name)


class Message(models.Model):
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def get_absolute_url(self, *args, **kwargs):
        return reverse('contact_detail_view', args=[self.contact.pk])

contact/forms.py
from django.forms import ModelForm
from django.conf import settings
from twilio.rest import Client

from .models import Contact, Message


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['first_name', 'last_name', 'number']


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['body']

    def send_sms(self, contact):
        number = contact.number
        client = Client(settings.TWILIO_SID, settings.TWILIO_AUTH)
        body = self.cleaned_data.get('body', 'No Message Provided')

        client.messages.create(
            to="+1" + number,
            from_=settings.TWILIO_NUMBER,
            body=body)

contact/views.py
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

from .models import Contact
from .forms import ContactForm, MessageForm


class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        if self.request.user.is_authenticated:
            context['contacts'] = Contact.objects.filter(owner=self.request.user)
            context['new_contact_form'] = ContactForm()
        return context


class ContactCreateView(CreateView):
    form_class = ContactForm
    success_url = '/'
    template_name = "contact/contact_create.html"

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ContactDetailView(DetailView):
    model = Contact

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['new_message_form'] = MessageForm()
        return context


class MessageCreateView(CreateView):
    form_class = MessageForm

    def form_valid(self, form):
        contact = Contact.objects.get(id=self.request.POST.get('contact_id', None))
        form.instance.contact = contact
        form.send_sms(contact)
        return super().form_valid(form)

contact/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Twilio SMS Contact Book</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  </head>
  <body>

    <!-- header -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">SMS Contacts</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          {% if not user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'register_view' %}">Signup</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body %}
      {% endblock body %}
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>

contact/templates/contact/contact_create.html
{% extends 'base.html' %}

{% block body %}
<br/>

<form action="{% url 'contact_create_view' %}" method="POST">
  {% csrf_token %}
  {{ form.as_p}}
  <input type="submit" value="Add New Contact" class="btn btn-primary"/>
</form>

{% endblock body %}

contact/templates/contact/contact_detail.html
{% extends 'base.html' %}

{% block body %}

<br/>
<p>
  <a href="{% url 'index_view' %}" class="btn btn-secondary">Go Back</a>
</p>

<h1>Contact: {{ object.full_name }}</h1>
<h2>Number: {{ object.number }}</h2>

<h3>Messages: </h3>
<ul>
{% for message in object.message_set.all %}
  <li>
    {{ message.body }} ( {{ message.created }} )
  </li>
{% empty %}
  <li>
    No messages yet, you should send one
  </li>
{% endfor %}
</ul>

<h3>Send {{ object.first_name }} a message</h3>

<form action="{% url 'message_create_view' object.pk %}" method="POST">
  {% csrf_token %}
  <input type="hidden" name="contact_id" value="{{ object.id }}">
  {% for field in new_message_form %}
    <p>
      {{ field }}
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    </p>
  {% endfor %}
  <input type="submit" value="Message" class="btn btn-primary" />
</form>

{% endblock body %}

contact/templates/index.html
{% extends 'base.html' %}

{% block body %}
{% if user.is_authenticated %}
  <h1>Welcome to your SMS Contact book</h1><br/>

  <h3>Existing Contacts</h3>
  <table class="table table-striped">
    <tr class="thead-dark">
      <th>Full Name</th>
      <th>Phone Number</th>
    </tr>
  {% for contact in contacts %}
    <tr>
      <td><a href="{% url 'contact_detail_view' contact.id %}">{{ contact.full_name }}</a></td>
      <td>{{ contact.number }}</td>
    </tr>
  {% empty %}
    <tr>
      <td colspan=2> It doesn't look like you have any contacts. You should add one. </td>
    </tr>
  {% endfor %}
  </table> <br/>


  <h3>Add a new Contact</h3>
  <form action="{% url 'contact_create_view' %}" method="POST">
    {% csrf_token %}
    {{ new_contact_form.as_p }}

    <input type="submit" value="Add New Contact" class="btn btn-primary"/>
  </form>

{% else %}

<br/>
<div class="jumbotron">
  <h1 class="display-4">Why, hello there.</h1>
  <p class="lead">It doesn't look like you're logged in. Maybe you should sign up for an account or login?</p>
</div>
{% endif %}
{% endblock body %}

contact/templates/register.html
{% extends 'base.html' %}

{% block body %}
<br/>
{% if form.errors %}
  <p>There were errors creating your account. Please try again.</p>
{% endif %}
<form action="{% url 'register_view' %}" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Signup" class="btn btn-primary"/>
</form>
{% endblock body %}